bind r source-file ~/.tmux.conf \; display " reloaded .tmux.config";

set -g prefix2 C-Space
bind C-Space send-prefix

set -g display-time 2400
set -g mouse on

set-option -g default-command "cd $(pwd); $SHELL"
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"