bind r source-file ~/.tmux.conf \; display " reloaded .tmux.config";

set -g prefix2 C-Space
bind C-Space send-prefix

set -g mouse on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:Tc"
set -g base-index 1
set -g pane-base-index 1
set -g history-limit 10000

set-option -g default-command "cd $(pwd); $SHELL"
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "wl-copy"

# tokyonight

set -g @primary "#5fd787"
set -g @secondary "#0087d7"
set -g @background "#171421"

set -g status-bg "#171421"
set -g status-style bold

set -g status-left-length 40
set -g status-left \
"#[fg=#{@background},bg=#{@secondary}] #(whoami)@#h •\
#[fg=#{@background},bg=#{@secondary}] #S \
#[fg=#{@secondary},bg=#{@background}]\
#[default\]"

set -g status-right-length 100
set -g status-right \
"#[fg=#{@secondary},bg=#{@background}]\
#[fg=#{@background},bg=#{@secondary}]#(cat /sys/class/power_supply/BAT0/capacity)% \
#[fg=#{@background},bg=#{@secondary}]%a %Y-%m-%d %H:%M \
#[default\]"

setw -g window-status-format \
"#[fg=#{?window_bell_flag,#f7768e,#{@background}},bg=#{@background}]\
#[fg=#{?window_bell_flag,#{@background},#{@secondary}},bg=#{?window_bell_flag,#f7768e,#{@background}}] #I\
#[fg=#{?window_bell_flag,#{@background},#{@secondary}},bg=#{?window_bell_flag,#f7768e,#{@background}}] #W \
#[fg=#{?window_bell_flag,#f7768e,#{@background}},bg=#{@background}]\
#[default\]"

setw -g window-status-current-format \
"#[fg=#{@primary},bg=#{@background}]\
#[fg=#{@background},bg=#{@primary},bold] #I\
#[fg=#{@background},bg=#{@primary}] #W \
#[fg=#{@primary},bg=#{@background}]\
#[default\]"

set -g pane-border-lines heavy
set -g pane-border-status top
set -g pane-border-style "fg=#{@secondary}"
set -g pane-active-border-style "fg=#{@primary},bold"
set -g message-style "bg=#{@primary},fg=#{@background},bold"
set -g display-time 2400